version: "3.7"

services:
  ##### Website & DAPR Sidecar #####
  worker:
    build:
      context: ./src/worker
      dockerfile: Dockerfile
    # env_file:
    #   - .env
    ports:
      - "5000:5000"
    logging: *default-logging

  worker_dapr:
    image: "daprio/daprd:1.2.2"
    command:
      [
        "./daprd",
        "-app-id",
        "worker",
        "-app-port",
        "80",
        "-config",
        "/dapr/config.yaml",
        "-components-path",
        "/dapr",
      ]
    volumes:
      - "./components:/dapr"
    depends_on:
      - worker
    network_mode: "service:worker"
    # env_file:
    #   - .env

networks:
  default:
    external:
      name: dapr_network
